FROM golang:1.24-alpine AS builder

WORKDIR /app

ENV GOPROXY=https://goproxy.cn,direct

COPY backend/go.mod backend/go.sum ./backend/
COPY backend ./backend

WORKDIR /app/backend

RUN go mod download
RUN CGO_ENABLED=0 go build -p 1 -o search_sync_worker.out ./cmd/search-sync-worker

FROM alpine:latest AS runner

WORKDIR /app

COPY --from=builder /app/backend/search_sync_worker.out .

CMD ["./search_sync_worker.out"]
