FROM golang:1.24-alpine AS builder

WORKDIR /app

ENV GOPROXY=https://goproxy.cn,direct

COPY backend/go.mod backend/go.sum ./backend/
COPY backend ./backend

WORKDIR /app/backend

RUN go mod download
RUN CGO_ENABLED=0 go build -p 1 -o snapshot_worker.out ./cmd/snapshot-worker

FROM alpine:latest AS runner

WORKDIR /app

COPY --from=builder /app/backend/snapshot_worker.out .

CMD ["./snapshot_worker.out"]
