# RabbitMQ Configuration File - Example

# Default user and password
default_user = guest
default_pass = guest

# Management plugin
management.tcp.port = 15672

# Networking
listeners.tcp.default = 5672

# Memory-based DB configuration
vm_memory_high_watermark.relative = 0.6

# Logging
log.file.level = info

# Additional security configurations
auth_mechanisms.plain = true
auth_mechanisms.amqplain = true
auth_mechanisms.external = false