FROM node:20-alpine AS builder

WORKDIR /app
COPY collab/package.json collab/package-lock.json* ./
RUN npm install

FROM node:20-alpine
WORKDIR /app
COPY --from=builder /app/node_modules ./node_modules
COPY collab/. .

EXPOSE 1234

CMD ["node", "server.js"]